# Generated by Django 4.2.18 on 2025-01-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('buyer', models.ManyToManyField(related_name='auto', to='task1.buyer')),
            ],
        ),
    ]
